// students/k3340/Rusinov_Vasiliy/lr4/src/components/LoginPage.vue
<script setup>
import {ref} from "vue";
import instance from "@/AxiosInstance";
import index from "@/router";
import {Api} from "@/services/api";

const Token = Api()

const form = ref({
  username: '',
  password: ''
})

function login(){
  instance.post('/auth/token/login', form.value).then(response => {
    if (response.status === 200){
      Token.setToken(response.data.auth_token)
      console.log(Token.token)
      index.push('/categories')
    }
  }
  ).catch(error => console.log(error))
}

</script>

<template>
  <v-app>
    <div class="w-50 mx-auto">
      <h2>Вход</h2>
    <v-text-field label="Логин" v-model="form.username"></v-text-field>
    <v-text-field label="Пароль" v-model="form.password"></v-text-field>
    <v-btn @click="login">Войти</v-btn>
    </div>
  </v-app>
</template>

<style scoped>

</style>

// Students/K3339/Prokopets Semen/Lr4/src/page/LoginPage.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useToken } from '../stores/token';
import axios from '../utils/axiosConfig';
import '../Css/LoginPage.css';
const LoginPage = () => {
    const [form, setForm] = useState({
        username: '',
        password: ''
    });
    const { setToken } = useToken();
    const navigate = useNavigate();

    const handleChange = (e) => {
        const { name, value } = e.target;
        setForm({
            ...form,
            [name]: value
        });
    };

    const login = async () => {
        console.log('Login button clicked');
        console.log('Form data:', form);
        try {
            const response = await axios.post('api/auth/token/login/', form);
            if (response.status === 200) {
                setToken(response.data.auth_token);
                navigate('/');
            }
        } catch (error) {
            console.error('Ошибка входа:', error.response?.data || error.message);
        }
    };

    const register = () => {
        navigate('/register');
    };

    return (
        <div className="login-container">
            <h2>Вход</h2>
            <input
                type="text"
                name="username"
                placeholder="Логин"
                value={form.username}
                onChange={handleChange}
                required
            />
            <input
                type="password"
                name="password"
                placeholder="Пароль"
                value={form.password}
                onChange={handleChange}
                required
            />
            <div className="button-container">
                <button onClick={login}>Войти</button>
                <button onClick={register}>Зарегистрироваться</button>
            </div>
        </div>
    );
};

export default LoginPage;
