// students/k3341/Iakynin_Andrey/lab4/src/pages/Login/Login.jsx
import React, { useState } from "react";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import "./Login.css";

const Login = () => {
    const [username, setUsername] = useState("");
    const [password, setPassword] = useState("");
    const [error, setError] = useState("");
    const [success, setSuccess] = useState("");
    const navigate = useNavigate();

    const handleLogin = async (e) => {
        e.preventDefault();
        setError("");
        setSuccess("");

        try {
            const response = await axios.post("http://127.0.0.1:8000/api/auth/token/login", {
                username,
                password,
            });

            const token = response.data.auth_token;

            // Сохраняем токен и имя пользователя в localStorage
            localStorage.setItem("authToken", token);
            localStorage.setItem("username", username);

            setSuccess("Login successful!");

            // Перенаправляем на главную страницу
            navigate("/");
        } catch (err) {
            setError("Invalid username or password.");
        }
    };

    return (
        <div className="login-container">
            <form className="login-form" onSubmit={handleLogin}>
                <h2>Login</h2>
                {error && <p className="error-message">{error}</p>}
                {success && <p className="success-message">{success}</p>}

                <div className="form-group">
                    <label htmlFor="username">Username</label>
                    <input
                        type="text"
                        id="username"
                        value={username}
                        onChange={(e) => setUsername(e.target.value)}
                        placeholder="Enter your username"
                        required
                    />
                </div>

                <div className="form-group">
                    <label htmlFor="password">Password</label>
                    <input
                        type="password"
                        id="password"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        placeholder="Enter your password"
                        required
                    />
                </div>

                <button type="submit" className="btn-login">
                    Login
                </button>
            </form>
        </div>
    );
};

export default Login;

// students/k3339/Berdichevskii_Artem/Lr4/src/views/Login.vue
<template>
  <div class="register-container">
    <h2>Login</h2>
    <form @submit.prevent="login">
      <div class="form-group">
        <label for="username">Username</label>
        <input
            type="text"
            id="username"
            v-model="username"
            class="form-control"
            autocomplete="username"
            required
        />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
            type="password"
            id="password"
            v-model="password"
            class="form-control"
            autocomplete="current-password"
            required
        />
      </div>
      <button type="submit" class="btn btn-primary">Log into your account</button>
    </form>
    <p v-if="error" class="text-danger mt-3">{{ error }}</p>
    <p v-if="success" class="text-success mt-3">{{ success }}</p>
  </div>
</template>

<script>
import axiosInstance from "@/services/axios";
import router from "@/router/index.js";
import {SetAuthToken} from '@/composables/token.js';

export default {
  name: "LoginView",
  data() {
    return {
      username: "",
      password: "",
      error: null,
      success: null,
    };
  },
  methods: {
    async login() {
      this.error = null;
      this.success = null;

      try {
        const response = await axiosInstance.post("auth/token/login/", {
          username: this.username,
          password: this.password,
        });
        console.log(response);
        const data = await response.data;
        this.success = "Login successful!";
        SetAuthToken(data['auth_token']);
        setTimeout(router.back(), 3)

      } catch (err) {
        this.error = err.response?.data || "Login failed.";
      }
    },
  },
};
</script>
