// Students/K3339/Prokopets Semen/Lr4/src/page/LoginPage.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useToken } from '../stores/token';
import axios from '../utils/axiosConfig';
import '../Css/LoginPage.css';
const LoginPage = () => {
    const [form, setForm] = useState({
        username: '',
        password: ''
    });
    const { setToken } = useToken();
    const navigate = useNavigate();

    const handleChange = (e) => {
        const { name, value } = e.target;
        setForm({
            ...form,
            [name]: value
        });
    };

    const login = async () => {
        console.log('Login button clicked');
        console.log('Form data:', form);
        try {
            const response = await axios.post('api/auth/token/login/', form);
            if (response.status === 200) {
                setToken(response.data.auth_token);
                navigate('/');
            }
        } catch (error) {
            console.error('Ошибка входа:', error.response?.data || error.message);
        }
    };

    const register = () => {
        navigate('/register');
    };

    return (
        <div className="login-container">
            <h2>Вход</h2>
            <input
                type="text"
                name="username"
                placeholder="Логин"
                value={form.username}
                onChange={handleChange}
                required
            />
            <input
                type="password"
                name="password"
                placeholder="Пароль"
                value={form.password}
                onChange={handleChange}
                required
            />
            <div className="button-container">
                <button onClick={login}>Войти</button>
                <button onClick={register}>Зарегистрироваться</button>
            </div>
        </div>
    );
};

export default LoginPage;

// students/k3340/Yaganova_Margarita/lab_4/insurance_app/src/views/LoginPage.vue
<template>
<div class="auth-container">
    <div class="card col-md-6">
    <div class="card-body">
        <form class="auth-form" id="entranceForm" @submit.prevent="handleLogin">
          <h2>Login</h2>
          <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input
              type="text"
              id="username"
              class="form-control"
              required
              v-model="username"
            />
          </div>
          <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" required v-model="password" />
          </div>
          <button type="submit" class="btn btn-primary">Log in</button>
        </form>
    </div>
    </div>
  </div>
</template>

<script>
import { login } from '@/services/authService';
import router from '@/router';

export default {
  data() {
    return {
      username: '',
      password: '',
    };
  },
  methods: {
    async handleLogin() {
      try {
        const token = await login(this.username, this.password)
        router.push({name: 'account'})
      } catch (error) {
        console.error(error);
    }
  },
}}
</script>

<style scoped>
.auth-container {
  display: flex;
  justify-content: center;
  margin-top: 5%;
}
</style>
