// students/k3341/laboratory_works/Khisametdinova_Dinara/laboratory_work_4/src/app/auth/register/register.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { trigger, transition, style, animate } from '@angular/animations';
import { CommonModule } from '@angular/common'
import { AuthService } from '../../services/auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  standalone: true,
  imports: [FormsModule, CommonModule],
  styleUrls: ['./register.component.css'],
  animations: [
    trigger('fadeIn', [
      transition(':enter', [
        style({ opacity: 0, transform: 'scale(0.9)' }),
        animate('300ms ease-out', style({ opacity: 1, transform: 'scale(1)' })),
      ]),
    ]),
  ],
})
export class RegisterComponent {
  user = {
    username: '',
    email: '',
    password: '',
    re_password: '',
    role: 'student',
    first_name: '',
    last_name: '',
  };
  submitted = false;
  errorMessage: string | null = null;

  constructor(private authService: AuthService, private router: Router) {}

  register() {  
    this.submitted = true;
    if (this.user.password !== this.user.re_password) {
      this.errorMessage = 'Passwords do not match!';
      return;
    }

    const userPayload = {
      username: this.user.username,
      email: this.user.email,
      password: this.user.password,
      re_password: this.user.re_password,
      role: this.user.role,
      first_name: this.user.first_name,
      last_name: this.user.last_name,
    };

    this.authService.register(userPayload).subscribe({
      next: () => {
        alert('You have successfully registered!');
        this.errorMessage = null;
        this.router.navigate(['/dashboard']);
      },
      error: (err) => {
        console.error(err);
        this.errorMessage = 'Registration failed. Please try again.';
      },
    });
  }
}

<div class="d-flex justify-content-center align-items-center vh-100 bg-light">
    <div class="card p-4 shadow-lg" style="width: 400px;">
      <h2 class="text-center mb-4">Register</h2>
      <form (ngSubmit)="register()" [class.was-validated]="submitted" novalidate>
        <div class="form-floating mb-3">
          <input
            type="text"
            id="username"
            name="username"
            class="form-control"
            placeholder="Username"
            [(ngModel)]="user.username"
            required
          />
          <label for="username">Username</label>
          <div class="invalid-feedback">Please enter a username.</div>
        </div>
        <div class="form-floating mb-3">
          <input
            type="email"
            id="email"
            name="email"
            class="form-control"
            placeholder="Email"
            [(ngModel)]="user.email"
            required
          />
          <label for="email">Email</label>
          <div class="invalid-feedback">Please enter a valid email.</div>
        </div>
        <div class="form-floating mb-3">
          <input
            type="password"
            id="password"
            name="password"
            class="form-control"
            placeholder="Password"
            [(ngModel)]="user.password"
            required
          />
          <label for="password">Password</label>
          <div class="invalid-feedback">Please enter a password.</div>
        </div>
        <div class="form-floating mb-3">
          <input
            type="password"
            id="re_password"
            name="re_password"
            class="form-control"
            placeholder="Confirm Password"
            [(ngModel)]="user.re_password"
            required
          />
          <label for="re_password">Confirm Password</label>
          <div class="invalid-feedback">Passwords must match.</div>
        </div>
        <div class="form-floating mb-3">
          <select
            id="role"
            name="role"
            class="form-select"
            [(ngModel)]="user.role"
            required
          >
            <option value="student">Student</option>
            <option value="teacher">Teacher</option>
          </select>
          <label for="role">Role</label>
          <div class="invalid-feedback">Please select a role.</div>
        </div>
        <div class="form-floating mb-3">
          <input
            type="text"
            id="first_name"
            name="first_name"
            class="form-control"
            placeholder="First Name"
            [(ngModel)]="user.first_name"
            required
          />
          <label for="first_name">First Name</label>
          <div class="invalid-feedback">Please enter your first name.</div>
        </div>
        <div class="form-floating mb-3">
          <input
            type="text"
            id="last_name"
            name="last_name"
            class="form-control"
            placeholder="Last Name"
            [(ngModel)]="user.last_name"
            required
          />
          <label for="last_name">Last Name</label>
          <div class="invalid-feedback">Please enter your last name.</div>
        </div>
        <button class="btn btn-primary w-100" type="submit">Register</button>
      </form>
      <div *ngIf="errorMessage" class="alert alert-danger mt-3">{{ errorMessage }}</div>
    </div>
  </div>

// students/k3343/Rakhmanov_Vladislav/Lr4/fitness_platform_web/fitness_platform_frontend/src/views/Register.vue
<script setup lang="ts">
import { ref } from "vue";
import {register} from "@/composables/AccountActions.ts";
import router from "@/router";

const form = ref({
  email: "",
  username: "",
  password: "",
  re_password: "",
});

const loading = ref(false);
const errorMessage = ref<string | null>(null);
const success = ref<string>("");

const submitForm = async () => {
  errorMessage.value = null;
  loading.value = true;
  if (form.value.password !== form.value.re_password) {
    loading.value = false;
    errorMessage.value = "Passwords do not match";
    return
  }
  try {
    await register(form.value.email, form.value.password, form.value.re_password, form.value.username);
    console.log("Registration successful");
    success.value = 'Registration successful. You will automatically log in and be redirected to home';
    setTimeout(() => {
      router.push("/");
    }, 3000);
  } catch (error: any) {
    errorMessage.value = error.response?.data?.detail || "Registration failed";
  } finally {
    loading.value = false;
  }
};
</script>

<template>
  <div class="d-flex justify-content-center align-items-center vh-100">
    <div class="card text-bg-dark p-4" style="width: 100%; max-width: 400px;">
      <h2 class="text-center mb-3">Register</h2>
      <form @submit.prevent="submitForm">
        <div class="mb-3">
          <label for="email" class="form-label">Email</label>
          <input
              id="email"
              v-model="form.email"
              type="email"
              class="form-control"
              required
          />
        </div>
        <div class="mb-3">
          <label for="username" class="form-label">Username</label>
          <input
              id="username"
              v-model="form.username"
              type="text"
              class="form-control"
              required
          />
        </div>
        <div class="mb-3">
          <label for="password" class="form-label">Password</label>
          <input
              id="password"
              v-model="form.password"
              type="password"
              class="form-control"
              required
          />
        </div>
        <div class="mb-3">
          <label for="re_password" class="form-label">Confirm Password</label>
          <input
              id="re_password"
              v-model="form.re_password"
              type="password"
              class="form-control"
              required
          />
        </div>
        <button type="submit" class="btn btn-primary w-100" :disabled="loading">
          {{ loading ? "Registering..." : "Register" }}
        </button>
        <p v-if="errorMessage" class="text-danger text-center mt-3">
          {{ errorMessage }}
        </p>
        <p v-if="success" class="text-center mt-3 text-success">
          {{ success }}
        </p>
      </form>
    </div>
  </div>
</template>

<style scoped>
.card {
  border-radius: 10px;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
}
</style>
